# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3242b120dfc8d2529a89aae75f95e3d5f23681a64b88fd1335202aa86a05645f3d34db4139a1dc303dd9d035f70619e4c5c80422e0bd977b77d7e1582b127ef

test:
  secret_key_base: 1a2147d8d9cc0de24b8a6c216225494a8b7061ec0974794b4dd529acd638ab4147a9c61cdca6b5cdb6325fd3f64dce84bcd8b62fabe8b86a1ed4deea518daab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
